#!/bin/sh
set -e

ROOT=`git rev-parse --show-toplevel`
cd $ROOT
mkdir -p bin
cd bin
cmake -DUSE_ASAN=ON -DENABLE_WARNINGS_AS_ERRORS=ON -DENABLE_TESTS=ON ..
make run_all_tests

cd $ROOT
mkdir -p bin_hidapi
cd bin_hidapi
cmake -DUSE_ASAN=ON -DENABLE_WARNINGS_AS_ERRORS=ON -DENABLE_TESTS=ON -DUSE_HIDAPI=On ..
make run_all_tests

cd $ROOT
make
