#!/bin/bash

if [ "$1" == "-m" ]; then
    `dirname $0`/survive-cli --record-stdout --record-cal-imu --no-record-imu $@
    exit $?
fi;

ROOT=`git rev-parse --show-toplevel`
echo -e -n 'Navigate to \e[32mfile://'
echo -n -e $ROOT
echo -e '/tools/viz/index.html\033[m '
websocketd --passenv OPENBLAS_NUM_THREADS --passenv HOME --port 8080 `dirname $0`/survive-cli --record-stdout --record-cal-imu --report-covariance 30 $@
